### ISSUE TITLE
Logo proposal for RxJS-Playground

### ISSUE THREAD

**Issue by baranpirincal** [JayKan/RxJS-Playground#2]
Hello! I want to contribute on your project with making logo design. What do you think about it? It can be logotype . If you interested we can talk about design choices. I am waiting your feedback! :grinning: 

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by JayKan** [comment]
Yes @baranpirincal I would love to get some help on some logo design! Please feel free to send a PR 👍

**Comment by baranpirincal** [comment]
Hey again @JayKan , I designed a logo inspired by RxJS original logo design, I hope you like it:

![rxjs playground](https://user-images.githubusercontent.com/37786733/39388858-f97a2164-4a8b-11e8-8bc0-359b0d68015d.jpg)

**Comment by JayKan** [comment]
@baranpirincal this is awesome man! Looks legit 👍 💯 I will merge this and close the PR later 😄

**Comment by JayKan** [comment]
@baranpirincal if they are more logos needed to be done, can I contact you haha?

**Comment by baranpirincal** [comment]
@jaykan I am happy you liked it :) I will create a pull request. Also, of course you can contact me if you need a logo design :) Have a nice day!

**Comment by JayKan** [comment]
@baranpirincal thanks a lot for your help!! Please send a PR when you get a chance 👍

**Comment by baranpirincal** [comment]
@JayKan I sent it, You're welcome! :+1:

**Comment by JayKan** [comment]
@baranpirincal PR has been merged; I can't express how awesome the new logo is, please take a look at the README when you get a chance to see your awesome work 💯

**Comment by JayKan** [comment]
@baranpirincal, if you have some time, I'd appreciate if you can come up some logo ideas on this project I had worked on: https://github.com/JayKan/angular2-instagram; let me know what you think, and feel free to open an issue or PR 😄

**Comment by JayKan** [comment]
close current issue thanks for awesome work @baranpirincal https://github.com/JayKan/RxJS-Playground/pull/3
